// <auto-generated />
using KeezzContractors.API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace KeezzContractors.API.Migrations
{
    [DbContext(typeof(KeezzContractorsContext))]
    [Migration("20171206102334_KeezzContractorsDBAddContractorCompany")]
    partial class KeezzContractorsDBAddContractorCompany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KeezzContractors.API.Entities.Contractor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContractorCompany")
                        .HasMaxLength(80);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<bool>("Inactive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Contractors");
                });

            modelBuilder.Entity("KeezzContractors.API.Entities.ContractorInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContractorId");

                    b.Property<DateTime>("ContractorInvDate");

                    b.Property<string>("ContractorInvNote")
                        .HasMaxLength(200);

                    b.Property<string>("ContractorInvRef")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("DaysBilled");

                    b.HasKey("Id");

                    b.HasIndex("ContractorId");

                    b.ToTable("ContractorInvoices");
                });

            modelBuilder.Entity("KeezzContractors.API.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContractorInvoiceId");

                    b.Property<int>("CurrencyId");

                    b.Property<double>("ExpenseAmount");

                    b.Property<DateTime>("ExpenseDate");

                    b.Property<int>("ExpenseHeaderId");

                    b.Property<string>("ExpenseNote");

                    b.Property<double>("ForeignAmount");

                    b.Property<bool>("GST");

                    b.Property<int>("KeezzInvId");

                    b.Property<bool>("OnBill");

                    b.Property<int>("ProjectId");

                    b.HasKey("Id");

                    b.HasIndex("ContractorInvoiceId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("KeezzContractors.API.Entities.ContractorInvoice", b =>
                {
                    b.HasOne("KeezzContractors.API.Entities.Contractor", "Contractor")
                        .WithMany("ContractorInvoices")
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KeezzContractors.API.Entities.Expense", b =>
                {
                    b.HasOne("KeezzContractors.API.Entities.ContractorInvoice", "ContractorInvoice")
                        .WithMany("Expenses")
                        .HasForeignKey("ContractorInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
